# Default values for config-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

# Use this only if you want to replace the default that is .Chart.Name as the name of all the objects.
nameOverride: ""

# Set to true if you want to disable the postgrest service
disablePostgrest: false 

image:
  repository: docker.io/flanksource/config-db
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

configChangeRetentionDays: 60
configAnalysisRetentionDays: 60

# a list of configmaps to load scrape rules from, the configmap should have a single entry called "config.yaml"
scrapeRuleConfigMaps:
  - config-db-rules
db:
  # Setting this to true will create a postgres stateful set for config-db to connect to.
  enabled: true
  secretKeyRef:
    create: true
    # Setting the name of the secret will disable secret creation in this chart and look for an existing secret (whose name is specified in this field) to mount.
    # When setting this up in a fresh environment as a standalone app, it's best to leave the value empty.
    name:
    # This is the key that either the secret will create(if secretRefKey is empty) or this is the key it'll look for in the secret(if secretRefKey is mentioned).
    # The name of the key is mandatory to set.
    key: DB_URL
  storageClass:
  storage:

ingress:
  enabled: false
  annotations:
    {}
    #  kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: config-db.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    memory: 4Gi
    cpu: 500m

serviceAccount:
  create: true
  name: ""
  annotations: {}

upstream:
  secretKeyRef:
    name: upstream
  agentName: 
  pageSize: 500

extra:
  {}
  # nodeSelector:
  #   key: value
  # tolerations:
  #   - key: "key1"
  #     operator: "Equal"
  #     value: "value1"
  #     effect: "NoSchedule"
  # affinity:
  #   nodeAffinity:
  #       requiredDuringSchedulingIgnoredDuringExecution:
  #         nodeSelectorTerms:
  #         - matchExpressions:
  #           - key: kubernetes.io/e2e-az-name
  #             operator: In
  #             values:
  #             - e2e-az1
  #             - e2e-az2
